### PR TITLE
Bug 570471 - Add utilities for perspectives persistence and migration

### PR DESCRIPTION
**Pull request by eneufeld**
Add new utilities which allow to

persist and restore perspectives in e4 applications including the
part's states
migrate 3.x perspectives to e4 applications
The code is split in two bundles, one contributing the persist and
restore functionality, the other contributing the 3.x to e4 perspective
migration.

Signed-off-by: Eugen Neufeld <eneufeld@eclipsesource.com>

### CODE REVIEW

**Comment by eneufeld** [comment]
This PR comes originally from https://github.com/eclipse-platform/eclipse.platform.ui/pull/29 .
There we had a long discussion about whether the platform.ui is a great fit, and the tools project was suggested as a better? alternative.

**Comment by vogella** [comment]
Thanks @eneufeld I plan to test once 4.25 opens up and merge if I find it ok.

**Comment by eneufeld** [comment]
Hi @vogella,
did you had a chance to take a look at this in the meantime?

Thank you for taking this on.

**Comment by JonasHelming** [comment]
Hi Lars (@vogella ) 
sorry to ping you again. Can you estimate when you might find the time to have a quick look at this?
Best regards,
Jonas

**Comment by vogella** [comment]
Sorry, for the delay on my side. As I seem not to find the time to review, just merge early for the next release, if you as committer are fine with these changes. 

For cases like this (in which I'm the one blocked by otherwise), I typically use the approach to set a deadline for new feedback after which I merge, e.g. "I have not received additinal feedback about this change, please raise concerns until (today + a few workdays). If no additional concern is raised, I will merge it."

**Comment by merks** [comment]
@eneufeld 

FYI, I don't think the build failure is caused by your changes.  It looks to be related to changes around jakarta/javax dependencies that in flux today.  I'll re-trigger the build when that issue appears to be resolved.  Feel free to ping me if it appears that I've forgotten.

**Comment by eneufeld** [comment]
Hi @merks , 
that was fast ;-) . Thank you for watching the builds.
Do you think the missing junit dependency is also caused by the changes around jakarta/javax?
It worked before my rebase or did I miss some update?

**Comment by merks** [comment]
Maybe these are only warnings:
```
[WARNING] Problems resolving provisioning plan.: [Unable to satisfy dependency from org.osgi.service.http 1.2.2.202109301733 to java.package; javax.servlet [2.1.0,3.0.0).; Unable to satisfy dependency from org.osgi.service.http 1.2.2.202109301733 to java.package; javax.servlet.http [2.1.0,3.0.0).; Unable to satisfy dependency from org.osgi.service.http.whiteboard 1.1.1.202109301733 to osgi.contract; (&(osgi.contract=JavaServlet)(version=3.1.0)).]
```
And indeed this is a problem:
```
[ERROR]   Software being installed: org.eclipse.e4.tools.compatibility.migration.tests 1.0.0.qualifier
[ERROR]   Missing requirement: org.eclipse.e4.tools.compatibility.migration.tests 1.0.0.qualifier requires 'osgi.bundle; org.junit.jupiter.api [5.8.0,6.0.0)' but it could not be found
```
Yes, that's not correct.  Probably you should use package imports because the bundle has a different name now:
```
			<dependency>
				<groupId>org.junit.jupiter</groupId>
				<artifactId>junit-jupiter-api</artifactId>
				<version>5.9.1</version>
				<type>jar</type>
			</dependency>
```
I only see JDT still used bundle dependencies, which look like this:
```
Require-Bundle: org.eclipse.jdt.junit.runtime;bundle-version="[3.5.0,4.0.0)",
 junit-jupiter-api;bundle-version="5.4.0",
 junit-jupiter-engine;bundle-version="5.4.0",
 junit-jupiter-migrationsupport;bundle-version="5.4.0",
 junit-jupiter-params;bundle-version="5.4.0",
 junit-vintage-engine;bundle-version="5.4.0",
 org.opentest4j;bundle-version="1.1.1",
 junit-platform-commons;bundle-version="1.4.0",
 junit-platform-engine;bundle-version="1.4.0",
 junit-platform-launcher;bundle-version="1.4.0",
 junit-platform-runner;bundle-version="1.4.0",
 junit-platform-suite-api;bundle-version="1.4.0",
 junit-platform-suite-commons;bundle-version="1.8.1",
 junit-platform-suite-engine;bundle-version="1.8.1",
 org.apiguardian.api;bundle-version="1.0.0",
 org.junit;bundle-version="4.12.0"
```
So yes, you should fix this and probably package imports would be best.

**Comment by merks** [comment]
@eneufeld I wonder if codeFormatting should be set to true in the *.genmodel?  I also wonder if the formatter settings are such that manual edits of the generated code (hopefully folks don't do so much of that) ends up formatting the whole file (which is okay, but hence the question about the generator also doing the formatter) but it's really bad if it formats the Javadoc.  That's been a real problem with other models and left things in a mess from which it was a lot of work (for me) to recover.

I'll try to find some time tomorrow to look closely....

**Comment by merks** [comment]
All the .project files are missing.  Please add them so that I can review this more easily.

**Comment by eneufeld** [comment]
> All the .project files are missing. Please add them so that I can review this more easily.

Sorry, they are ignored because of the .gitignore file and I missed that when creating the PR. 
Added them now.

**Comment by merks** [comment]
Please change the persistence.genmodel to the text in this attachment:

[persistence.genmodel.txt](https://github.com/eclipse-platform/eclipse.platform.ui.tools/files/10206567/persistence.genmodel.txt)

Then use it to regenerate the model.   These *.genmodel changes ensure that Generate All will only generate the model project not the other projects.   It does not update the classpath so the MANIFEST.MF doesn't change.  It does formatting and cleanup actions during generation so that the generated files match what might happen later if someone edits for formats them.  The compliance is set to 11 instead of 8 too.

Also please change  the file /org.eclipse.e4.tools.persistence/.settings/org.eclipse.jdt.core.prefs for this line:
```
org.eclipse.jdt.core.formatter.comment.format_javadoc_comments=false
```
Test that Ctrl-Shift-F, i.e., formatting a generated file **does not** mangle the Javadoc comments.

If you force push these changes, I'll review further in more detail...

**Comment by merks** [comment]
One more trivial thing.  For each project, create  `<project>/.settings/org.eclipse.core.resources.prefs` with the contents:
```
eclipse.preferences.version=1
encoding/<project>=UTF-8
```
to suppress the warning about this being missing.

Otherwise, technically everything seems in order...

@vogella 

I don't know if there needed to be any  '@since' annotations.  Otherwise, everything looks fine to me.

**Comment by eneufeld** [comment]
@merks Thank you for taking time looking at the PR.

**Comment by merks** [comment]
@vogella Do you plan to review this further?

**Review by JonasHelming — APPROVED** [review]

**Comment by vogella** [comment]
@JonasHelming please merge if you did the review

**Comment by vogella** [comment]
Thanks @JonasHelming @eneufeld and @merks 

Can you add information how to use these tools to the N&N document?

**Comment by eneufeld** [comment]
@vogella ,
good point I will open a PR for this

**Comment by eneufeld** [comment]
Hi @vogella , @merks ,

it seems I missed a necessary PR somewhere as the new packages are build : 
https://download.eclipse.org/eclipse/downloads/drops4/I20230214-1800/compilelogs/plugins/org.eclipse.e4.tools.persistence_1.0.0.v20221220-0825/@dot.html
but they are not part of the p2 repo:
https://download.eclipse.org/eclipse/updates/4.27-I-builds/I20230214-1800/plugins/

Could you help me out, what am I missing?

Thank you!

**Comment by eneufeld** [comment]
To answer my own question, I need to add them to this file: https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/category.xml

**Comment by iloveeclipse** [comment]
@eneufeld : if you will be fast, your PR can make into M3 (tomorrow build).

**Comment by iloveeclipse** [comment]
Correction: it will be today's last build.

**Pull request merged**
