### PR TITLE
Model Spy List tab not accessible with keyboard only #2

### PR DESCRIPTION
**Pull request by vik-chand**
Signed-off-by: Vikas Chandra <Vikas.Chandra@in.ibm.com>

### CODE REVIEW

**Comment by akurtakov** [comment]
Haven't you just merged it as #3 ?

**Comment by vik-chand** [comment]
> Haven't you just merged it as #3 ?

This is a backport for 4.23

**Comment by akurtakov** [comment]
Sorry, I missed that.

**Comment by akurtakov** [comment]
Please don't create branches in this repo like that. It is recommended to use branches in your own fork and submit PR unless you really expect to work with some other committer on the given issue.

**Comment by iloveeclipse** [comment]
> Please don't create branches in this repo like that. It is recommended

*Where* it is recommended? I assumed we don't need any rules / recommendations / wikis etc and can use "default" github workflows, and that one doesn't say anything specific about that: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by akurtakov** [comment]
It's here - https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/getting-started/about-collaborative-development-models . Shared repository model - "This model is more prevalent with small teams and organizations collaborating on private projects." and I would not call Eclipse being small team nor private project.

**Comment by laeubi** [comment]
I also like to cite this (from my point of view more important) section (**emphasis** by me):

> This model is popular with open source projects as it reduces the amount of friction for new contributors and **allows people to work independently without upfront coordination**.

So you don't _loose_ anything not pushing to the "main" repository but you _gain_ a lot e.g. you can name your branches as you like without any collision with other users, force push as you like, keep experiment branches even without open a PR at all and you even don't need committer access to work on this and so on.

And even if someday we decide to close/delete the repository you won't loose any of your work (as it might be when closing gerrit ...)

**Comment by merks** [comment]
I really feel that it would be good to have clearly spelled out guidelines for how we expect our committers and contributors to work.  

E.g., I expect we mostly want to have commits be tracked to an issue and that the form in which that issue is referenced is kind of important.  E.g., a commit like this one has a link that you can navigate with EGit even today.

https://github.com/eclipse-platform/eclipse.platform.team/commit/b90c87fc824d1e1b07625e7e7772b3e930ff0e7d

The link to the pull request is added too, but EGit doesn't help make that navigable...

**Pull request merged**
